# Generated by Django 4.2.16 on 2024-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(verbose_name='HTML содержимое слайда')),
                ('index', models.IntegerField(verbose_name='Порядковый номер слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['index'],
            },
        ),
    ]
