# Generated by Django 4.2.16 on 2024-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название слайда'),
        ),
    ]
