# Generated by Django 4.2.16 on 2024-09-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slide_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slide_images/', verbose_name='Медиа картинка'),
        ),
    ]
