# Generated by Django 4.2.16 on 2024-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_slide_image_slide_image_fon_slide_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image_fon',
        ),
        migrations.AddField(
            model_name='slide',
            name='image_background',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Фон слайда'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Превью'),
        ),
    ]
