# Generated by Django 4.2.16 on 2024-09-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_presentation_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slides_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Слайды'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slides',
            field=models.JSONField(blank=True, default='[\n        {\n            "template": "titleSlide",\n            "content": {\n                "1": "Заголовок",\n            }\n        },\n    ]', null=True, verbose_name='Слайды'),
        ),
    ]
