# Generated by Django 4.2.16 on 2024-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_theme_slides_json_alter_presentation_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='comments',
            field=models.JSONField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='slides',
            field=models.JSONField(blank=True, null=True, verbose_name='Слайды'),
        ),
    ]
